name: Forge
options:
  bundleIdPrefix: com.forge
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Automatic

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: 7.0.0
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: 2.0.0
  Markdown:
    url: https://github.com/swiftlang/swift-markdown
    from: 0.4.0
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: 2.0.0

targets:
  Forge:
    type: application
    platform: macOS
    sources:
      - Forge
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.forge.app
        INFOPLIST_FILE: Forge/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: Forge/Resources/Forge.entitlements
    dependencies:
      - package: GRDB
      - package: KeyboardShortcuts
      - package: Markdown
      - package: MarkdownUI
    entitlements:
      path: Forge/Resources/Forge.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.network.client: true
        com.apple.security.personal-information.location: false
        com.apple.security.automation.apple-events: true

schemes:
  Forge:
    build:
      targets:
        Forge: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
